### ISSUE TITLE
Fix compatibility with aiohttp3

### ISSUE THREAD

**Issue by alexazhou** [aio-libs/aioga#4]
Aiohttp3 replaces the built-in timeout method with the async-timeout module
-----------

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    loop.run_until_complete(go())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "test.py", line 13, in go
    ga.event(str(cid), ec='tests', ea='success from context manager')
  File "/usr/local/lib/python3.6/site-packages/aioga/__init__.py", line 129, in __aexit__
    yield from self.close()
  File "/usr/local/lib/python3.6/site-packages/aioga/__init__.py", line 118, in close
    yield from asyncio.gather(*self.futs, loop=self.loop)
  File "/usr/local/lib/python3.6/site-packages/aioga/__init__.py", line 65, in __request
    with aiohttp.Timeout(self.timeout, loop=self.loop):
### AttributeError: module 'aiohttp' has no attribute 'Timeout'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10f2abba8>

**Comment by asvetlov** [comment]
Thanks for the report.
Please check out aioga==0.1

**Comment by alexazhou** [comment]
Thank you,  aioga 0.1.0 works fine now
